# Generated by Django 2.2.7 on 2019-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0004_auto_20191126_1744'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='addnum',
#            name='Monthly_Balance',
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.IntegerField(default=0),
#        ),
#        migrations.RemoveField(
#            model_name='addnum',
#            name='Monthly_Interest',
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.IntegerField(default=0),
#        ),
    ]
