# Generated by Django 2.2.7 on 2019-11-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0007_auto_20191126_1959'),
    ]

    operations = [
#        migrations.AlterModelTable(
#            name='addnum',
#            table=None,
#            table='django_db',
#            table='django_db',
#        ),
    ]
