# Generated by Django 2.2.7 on 2019-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0008_auto_20191126_2106'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.Field(default='default', verbose_name='self'),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.Field(default='default', verbose_name='self'),
#            preserve_default=False,
#        ),
    ]
