# Generated by Django 2.2.7 on 2019-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0011_auto_20191127_1924'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.IntegerField(default=0),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.IntegerField(default=0),
#        ),
    ]
