# Generated by Django 2.2.7 on 2019-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0013_auto_20191127_1940'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Balance'),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Interest'),
#            preserve_default=False,
#        ),
    ]
