# Generated by Django 2.2.7 on 2019-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0020_auto_20191206_1402'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Monthly_Balance'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Monthly_Interest'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Loan_Balance',
#            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/', verbose_name='Monthly_Loan_Balance'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Loan_Interest',
#            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/', verbose_name='Monthly_Loan_Interest'),
#        ),
    ]
