# Generated by Django 2.2.6 on 2019-11-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Price', models.IntegerField(verbose_name='Purchase_Price')),
                ('Deposit_Paid', models.IntegerField(verbose_name='Deposit_Paid')),
                ('Bond_Term', models.IntegerField(verbose_name='Bond_Term')),
                ('Fixed_Interest_Rate', models.IntegerField(verbose_name='Fixed_Interest_Rate')),
                ('Name', models.CharField(verbose_name='Name')),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('Occupation', models.CharField(verbose_name='Occupation')),
#                ('Monthly_Interest', models.IntegerField(verbose_name='Monthly_Interest')),
#                ('Monthly_Balance',  models.IntegerField(verbose_name='Monthly_Balance')),
            ],
            options={
                'db_table': 'addnum',
            },
        ),
    ]
