# Generated by Django 2.2.6 on 2019-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnum',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
