# Generated by Django 2.2.7 on 2019-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0002_auto_20191118_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnum',
            name='Age',
            field=models.IntegerField(default=0, max_length=20, verbose_name='Age'),
            preserve_default=False,
        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.ManyToManyField('addnum'),
#            field=models.IntegerField(default=0, max_length=20, verbose_name='Monthly_Balance'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.ManyToManyField('addnum'),
#            field=models.IntegerField(default=0, max_length=20, verbose_name='Monthly_Interest'),
#        ),
        migrations.AddField(
            model_name='addnum',
            name='Occupation',
            field=models.CharField(default=0, max_length=20, verbose_name='Occupation'),
            preserve_default=False,
        ),
    ]
