# Generated by Django 2.2.7 on 2019-11-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0005_auto_20191126_1835'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.Addnum'),
#        ),
#        migrations.RemoveField(
#            model_name='addnum',
#            name='Monthly_Interest',
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.ManyToManyField(related_name='_addnum_Monthly_Interest_+', to='myapp_1.Addnum'),
#        ),
    ]
