# Generated by Django 2.2.7 on 2019-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0006_auto_20191126_1956'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='addnum',
#            name='Monthly_Balance',
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.ManyToManyField(related_name='_addnum_Monthly_Balance_+', to='myapp_1.Addnum'),
#            field=models.ManyToManyField(related_name='addnum.Monthly_Balance', to='myapp_1.Addnum.Monthly_Balance'),
#
#        ),

    ]
