# Generated by Django 2.2.7 on 2019-11-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0009_auto_20191127_1842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addnum',
#            table=None,
            table='',
        ),
    ]
