# Generated by Django 2.2.7 on 2019-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0014_auto_20191127_1948'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Balance'),
#        ),
#        migrations.AlterField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Interest'),
#        ),
    ]
