# Generated by Django 2.2.7 on 2019-11-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0015_auto_20191127_1953'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Balance'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.IntegerField(null=True, verbose_name='Monthly_Interest'),
#        ),
        migrations.AlterModelTable(
            name='addnum',
            table=None,
        ),
    ]
