# Generated by Django 2.2.7 on 2019-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0018_auto_20191204_1033'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Balance',
#            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Monthly_Balance'),
#        ),
#        migrations.AddField(
#            model_name='addnum',
#            name='Monthly_Interest',
#            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Monthly_Interest'),
#        ),
    ]
